language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key: 350800c3-2940-471a-99dc-5b4bafe93212
  app: andy-address
  on:
    repo: andrewcrane18/addressbook
    branch: todo_tasks
